### ISSUE TITLE
适配API23的权限管理

### ISSUE THREAD

**Issue by aesean** [liangzhitao/MessageSend#1]
AudioRecorder类中的MediaRecorder在API23中需要权限申请，否则会报java.lang.RuntimeException: setAudioSource failed.异常。

**Comment by liangzhitao** [comment]
多谢反馈，晚上回去我在 23 的机器上看看。

**Comment by liangzhitao** [comment]
已经在 demo 里做了修复了，用到了 https://github.com/anthonycr/Grant 这个库，可以很方便的处理权限请求，你可以再看看。
